version: '3.9'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend
    ports:
      - "8000:8000"
    networks:
      - app_network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend
    ports:
      - "8501:8501"
    networks:
      - app_network
    environment:
      - BACKEND_URL=http://backend:8000  # Communicates with the backend

networks:
  app_network:
    driver: bridge
